server:
  port: 8889
spring:
  application:
    name: register-center2
  profiles:
    active: peer2
eureka:
   instance:
     hostname: peer2
#   server:
#     eviction-interval-timer-in-ms: 5000
   client:
#     register-with-eureka: false
#     fetch-registry: false
     service-url:
        defaultZone: http://peer1:8888/eureka/

