server:
  port: 8888
eureka:
   instance:
     hostname: localhost
     lease-renewal-interval-in-seconds: 3
     lease-expiration-duration-in-seconds: 7
     statusPageUrl: http://${eureka.instance.hostname}/info
     healthCheckUrl: http://${eureka.instance.hostname}/health
     homePageUrl: http://${eureka.instance.hostname}/
   client:
     register-with-eureka: false
     fetch-registry: false
     service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
