server:
  port: 8888
spring:
  datasource:
    username: admin
    password: admin
  application:
    name: register-center1
  profiles:
    active: peer1
eureka:
   instance:
     hostname: peer1
   client:
     service-url:
        defaultZone: http://peer2:8889/eureka/


