server:
  port: 8280
spring:
  application:
    name: user-pay
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
       defaultZone: http://peer1:8888/eureka/,http://peer2:8889/eureka/