server:
  port: 5000
spring:
  application:
    name: api-gateway
zuul:
    routes:
       user-service:
         path: /user/**
         serviceId: user-service
    ignore-local-service: true
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8888/eureka/,http://peer2:8889/eureka/